# Model

# Word Embedding using TF-IDF
The model shall give recommendations based on the book title and description. Before building any NLP model, we need to convert the text data to numerical data in a meaningful way. Such word embedding techniques are: <br>
1. Bag of words <br>
2. TF-IDF <br>
3. Word2vec <br>
4. Latent Semantic Analysis encoding <br>

For this model we use TF-IDF short for term frequency–inverse document frequency, is a numerical statistic that is intended to reflect how important a word is to a document.

## Import libraries

In [82]:
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd
from sklearn.metrics.pairwise import linear_kernel

## Import test dataframe

In [120]:
df=pd.read_csv('DataFinal\Datatotestmodel.csv',index_col=0)
df.head()
#df.loc[4156,:]

title series  \
283                               Mistress Suffragette   none   
350                         Stones (One True Child #5)   none   
355                                   Mission: Subhero   none   
356  A Summer of Good-Byes (Blue Triangle Press Boo...   none   
357                                  The Scopas Factor   none   

                authors           isbn  \
283      Diana   Forbes     1946409073   
350           L.C. Conn              0   
355  Linda    Armstrong              0   
356      Fred Misurella              0   
357  Vincent Panettiere  9781543947717   

                                                genres  \
283  Fiction, Novels, Drama, Contemporary, Historic...   
350    Book Club, Novels, Fiction, Drama, Contemporary   
355  Contemporary, Novels, Fiction, Drama, Book Clu...   
356  Fiction, Novels, Adult, Contemporary, Adventur...   
357  Fiction, Contemporary, Novels, Drama, Book Clu...   

                                           description  pages  year language  \
283  A young woman without prospects at a ball in G...    333  2017  English   
350  Deep within the New Zealand bush, lies a plate...    327  2019  English   
355  With just a few lines of code, one average man...    225  2017  English   
356  PASSION IN PROVENCE:Ben and Lee Alto follow Va...      0  2017  English   
357  A Hmong "story cloth," a Revolutionary War bat...    326  2018  English   

                                           cover_image  total_number_ratings  \
283  https://i.gr-assets.com/images/S/compressed.ph...                 12973   
350  https://i.gr-assets.com/images/S/compressed.ph...                   569   
355  https://i.gr-assets.com/images/S/compressed.ph...                  2417   
356  https://i.gr-assets.com/images/S/compressed.ph...                  1713   
357  https://i.gr-assets.com/images/S/compressed.ph...                  1080   

     average_rating                              title_tokenized  \
283            4.32                         mistress suffragette   
350            4.31                      stones one true child 5   
355            4.35                              mission subhero   
356            4.36  summer good byes blue triangle press book 2   
357            4.31                                scopas factor   

                                desccription_tokenized  
283  young woman without prospects ball gilded age ...  
350  deep within new zealand bush lies plateau clea...  
355  lines code one average man change world and se...  
356  passion provence ben lee alto follow van goghs...  
357  hmong story cloth revolutionary war battle fla...

## Reset index and give index column the name 'book_id' - Question

In [121]:
#reset index and give index column the name 'book_id'
df.reset_index(drop=True, inplace=True)
df.reset_index(drop=False, inplace=True)
#df.index.name = 'book_id'
df.rename(columns = {'index':'book_id'}, inplace = True)
df

book_id                                              title  \
0           0                               Mistress Suffragette   
1           1                         Stones (One True Child #5)   
2           2                                   Mission: Subhero   
3           3  A Summer of Good-Byes (Blue Triangle Press Boo...   
4           4                                  The Scopas Factor   
...       ...                                                ...   
8134     8134                                   The Stove-Junker   
8135     8135                                     The Treemakers   
8136     8136        100 Years: A Journey to End a Vicious Cycle   
8137     8137    Thrive: 30 Inspirational Rags-to-Riches Stories   
8138     8138                                  The Smoke at Dawn   

                                        series               authors  \
0                                         none        Diana   Forbes   
1                                         none             L.C. Conn   
2                                         none    Linda    Armstrong   
3                                         none        Fred Misurella   
4                                         none    Vincent Panettiere   
...                                        ...                   ...   
8134                                      none            S.K. Kalsi   
8135                 The Treemakers Trilogy #1  Christina L. Rozelle   
8136                                      none       Mark L. Baynard   
8137                                      none         Jason Navallo   
8138  Civil War: 1861-1865, Western Theater #3           Jeff Shaara   

               isbn                                             genres  \
0        1946409073  Fiction, Novels, Drama, Contemporary, Historic...   
1                 0    Book Club, Novels, Fiction, Drama, Contemporary   
2                 0  Contemporary, Novels, Fiction, Drama, Book Clu...   
3                 0  Fiction, Novels, Adult, Contemporary, Adventur...   
4     9781543947717  Fiction, Contemporary, Novels, Drama, Book Clu...   
...             ...                                                ...   
8134  9780990779063                                               none   
8135     1508840466  Science Fiction, Dystopia, Fantasy, Young Adul...   
8136  9780986138003                                               none   
8137     1511503882  Nonfiction, Self Help, Inspirational, Business...   
8138  9780345527417  Historical, Historical Fiction, Military Histo...   

                                            description  pages  year language  \
0     A young woman without prospects at a ball in G...    333  2017  English   
1     Deep within the New Zealand bush, lies a plate...    327  2019  English   
2     With just a few lines of code, one average man...    225  2017  English   
3     PASSION IN PROVENCE:Ben and Lee Alto follow Va...      0  2017  English   
4     A Hmong "story cloth," a Revolutionary War bat...    326  2018  English   
...                                                 ...    ...   ...      ...   
8134  In the winter of 2012, 79-year-old Somerset Ga...    338  2015  English   
8135  This is a previously-published alternate cover...    288  2014  English   
8136  100 Years, A Journey to End a Vicious Cycle is...    290  2015  English   
8137  Thrive: 30 Inspirational Rags-to-Riches Storie...    100  2015  English   
8138  NEW YORK TIMESBESTSELLERJeff Shaara returns to...    495  2014  English   

                                            cover_image  total_number_ratings  \
0     https://i.gr-assets.com/images/S/compressed.ph...                 12973   
1     https://i.gr-assets.com/images/S/compressed.ph...                   569   
2     https://i.gr-assets.com/images/S/compressed.ph...                  2417   
3     https://i.gr-assets.com/images/S/compressed.ph...                  1713   
4     https://i.gr-assets.com/images/S/compressed.ph...  

## Concat columns title_tokenized, desccription_tokenized, series, author???)

In [122]:
#Check if there are still empty rows in column title_tokenized
df1=df[~df['title_tokenized'].isnull()]
df1.shape

(8139, 15)

In [123]:
#Concat 

## Model based on concat column with CountVectorizer and Cosine Similarity - change to concat column

In [124]:
df1=df1[~df1['desccription_tokenized'].isnull()]
df1.shape

(8139, 15)

In [125]:
#1.Step - convert the description from title_tokenized to a matrix of word counts
cm = CountVectorizer().fit_transform(df1['desccription_tokenized'])

In [126]:
#2.Get the cosine_simmilarity from the count matrix
cs = cosine_similarity(cm)
#print scores
print(cs)

[[1.         0.03698001 0.01391105 ... 0.03434824 0.01182625 0.02710247]
 [0.03698001 1.         0.06687598 ... 0.12384435 0.01421338 0.04885968]
 [0.01391105 0.06687598 1.         ... 0.05590493 0.02138701 0.04901308]
 ...
 [0.03434824 0.12384435 0.05590493 ... 1.         0.06336889 0.01210199]
 [0.01182625 0.01421338 0.02138701 ... 0.06336889 1.         0.01388922]
 [0.02710247 0.04885968 0.04901308 ... 0.01210199 0.01388922 1.        ]]


**Example of recommendation**

In [136]:
#Get example title to use
title_user = df1['title'][8135]
title_user

'The Treemakers'

In [137]:
indices = df1[df1.title == title_user]['book_id'].values[0]
print (indices)

8135


In [138]:
#Find the index of the book the user likes
#def find_indices(title_user):
 #   try:
  #      indices = df1[df1.title == title_user].index.values.astype(int)[0]#.index
   #     return indices
    #except:
     #   return('no match')

In [139]:
#find_indices(title_user)

In [140]:
#Create a list of tuples in the form (index,similarity)
scores = list(enumerate(cs[indices]))
print(scores)

[(0, 0.051058950386272096), (1, 0.06136522122969196), (2, 0.08207718821091448), (3, 0.11362181425944161), (4, 0.05227965541288916), (5, 0.09042434765989377), (6, 0.02987654747893084), (7, 0.04528829447956356), (8, 0.06756088501285375), (9, 0.047429066551892975), (10, 0.03996355400446205), (11, 0.04556130777011137), (12, 0.11629190608542939), (13, 0.017770232515462146), (14, 0.06806844829666249), (15, 0.038303421449880394), (16, 0.08419238894279374), (17, 0.029533971318100448), (18, 0.03840534664723373), (19, 0.056054286837216985), (20, 0.030425087235315493), (21, 0.05771277283986525), (22, 0.0), (23, 0.09283030967125735), (24, 0.03636915748463978), (25, 0.007324091278550464), (26, 0.03542922699584359), (27, 0.052491744135317014), (28, 0.017444145500654453), (29, 0.06730641749843791), (30, 0.09010904735887755), (31, 0.04528829447956356), (32, 0.014669093606372426), (33, 0.0), (34, 0.05394101453980999), (35, 0.10933696824052097), (36, 0.04082691210524657), (37, 0.04511660793609089), (38,

In [141]:
# Sort the list of similar books in descending order
sorted_score = sorted(scores, key=lambda x:x[1], reverse=True)
sorted_score = sorted_score[1:]
sorted_score

[(3608, 0.27537961164830244),
 (6219, 0.19485080736301058),
 (7982, 0.19214196080923604),
 (7920, 0.185846216514448),
 (3429, 0.1832730977500594),
 (2212, 0.18295574149853927),
 (6967, 0.18237054914243922),
 (2754, 0.18148770544641574),
 (5258, 0.17974790731133056),
 (762, 0.17591632680922945),
 (3438, 0.1755283281698721),
 (4151, 0.1753296020608784),
 (3247, 0.17487263544795584),
 (3818, 0.17444145500654454),
 (4433, 0.17305249870193834),
 (954, 0.17211968663971072),
 (7110, 0.17014538355063824),
 (7065, 0.16864949810750215),
 (3688, 0.16476370374010785),
 (481, 0.16327213878106323),
 (2884, 0.16276115607905084),
 (5152, 0.162615439450142),
 (1889, 0.16230401957157725),
 (724, 0.16215704406480622),
 (942, 0.16215704406480622),
 (6215, 0.16211269585527338),
 (518, 0.16185211449788595),
 (3046, 0.1614993368559911),
 (2098, 0.1605155753967385),
 (483, 0.15968330187499813),
 (2771, 0.1592589490283659),
 (784, 0.15910714368548076),
 (8042, 0.15885006786840208),
 (7594, 0.15844431990595387)

In [143]:
# Create a loop to print the first 5 books from the sorted list
j=0
print('The 5 most recommended books to '+title_user+' are:\n')
for item in sorted_score:
    book_title = df1[df1.book_id == item[0]]['title'].values[0]
    print(j+1, book_title)
    j=j+1
    if j >=5:
        break
#Missing to print cover_url

The 5 most recommended books to The Treemakers are:

1 Surprised by Joy: The Shape of My Early Life
2 Dreams of Joy
3 Scarred for Life: A Boy's Brutal Suffering and a Man's Raging Regret
4 An Accidental Affair
5 Archer's Voice


In [144]:
df1.loc[1314,:]

book_id                                                                1314
title                                                                  Room
series                                                                 none
authors                                                       Emma Donoghue
isbn                                                              316098329
genres                    Fiction, Contemporary, Adult, Adult Fiction, T...
description               To five-year-old-Jack, Room is the world....To...
pages                                                                   321
year                                                                   2010
language                                                            English
cover_image               https://i.gr-assets.com/images/S/compressed.ph...
total_number_ratings                                                 767812
average_rating                                                         4.06
title_tokeni

## Model with TfidfVectorizer

In [ ]:
tf = TfidfVectorizer(analyzer='word', ngram_range=(2, 2), min_df = 1, stop_words='english')
tfidf_matrix = tf.fit_transform(df1['title_tokenized'])

In [ ]:
# Calculating the similarity measures based on Cosine Similarity
sg = sk.cosine_similarity(tfidf_matrix, tfidf_matrix)
sg  

In [ ]:
# Get the index corresponding to original_title
indices = pd.Series(df1.index, index = df1['title_tokenized'])      
idx = indices[0]# Get the pairwsie similarity scores 
sig = list(enumerate(sg[idx]))# Sort the books
sig = sorted(sig, key=lambda x: x[1], reverse=True)# Scores of the 5 most similar books 
sig = sig[1:6]# Book indicies
movie_indices = [i[0] for i in sig]
   
    # Top 5 book recommendation
rec = df1[['title']].iloc[movie_indices]
rec 

In [ ]:
user = pd.DataFrame({'year':year,
                     'genre':genre,
                     'author':author,
                     'rating':rating,
                     'series':series}, index[0])

## Deal with author, gender

In [ ]:
split in multiple columns: if input is in column1,2,3?
    
Or explode aber dann gibt es wohl mehrmals die selbe Recommendation ...

In [ ]:
 #Search for title in database (options in streamlit that proposes the book title?)
def recommender(title):
    #reset index based on choices
   # df1.reset_index()
    #df1.reset_index() 
  
    # Convert the index into series
    indices = pd.Series(df1.index, index = df1['title'])
    
    tf = TfidfVectorizer(analyzer='word', ngram_range=(2, 2), min_df = 1, stop_words='english')
    tfidf_matrix = tf.fit_transform(df1['title_tokenized'])
    
    # Calculating the similarity measures based on Cosine Similarity
    sg = sk.cosine_similarity(tfidf_matrix, tfidf_matrix)
    
    # Get the index corresponding to original_title
    idx = indices[title]# Get the pairwsie similarity scores 
    sig = list(enumerate(sg[idx]))# Sort the books
    sig = sorted(sig, key=lambda x: x[1], reverse=True)# Scores of the 6 most similar books 
    sig = sig[1:6]# Book indicies
    book_indices = [i[0] for i in sig]
   
    # Top 5 book recommendation
    rec = df1['title'].iloc[book_indices]
       
    # It reads the top 6 recommended book urls and print the images
    
   ## for i in rec['url']:
     #   response = requests.get(i)
      #  img = Image.open(BytesIO(response.content))
       # plt.figure()
        #print(plt.imshow(img))
    return rec
    
   
    

In [ ]:
df1#.drop(['index'], axis = 1)

In [ ]:
recommender('Mission: Subhero')

In [ ]:
#column "pages" (Later EDA: Replace 0 with mean)
#Replace 'None' 0, EDA: Fill later with mean 
#funct.fillup_mean('pages')
funct.replace_in_column(cleaningdata,'pages','None','0')
cleaningdata['pages'].value_counts()